__author_email__ = 'maintainers@eveinsight.net'
__description__ = 'ESI celery task queues for distributed API access using RabbitMQ and Redis.'
__license__ = 'GNU General Public License v3.0'
__title__ = 'ESICelery'
__url__ = 'https://github.com/EVEInsight/ESICelery'
__version__ = '0.13'
